deployment:
  tasks:
    - export DEPLOY_ENV=production
    - /bin/cp -r * public_html/  # Copy all files to public_html
    - find public_html/ -type f -exec chmod 644 {} \;  # Set correct file permissions
    - find public_html/ -type d -exec chmod 755 {} \;  # Set correct folder permissions

cron:
  jobs:
    - schedule: "0 0 * * *"
      command: "/usr/bin/php /home/your_user/public_html/path/to/script.php"

env:
  variables:
    - name: API_KEY
      value: "your_api_key_here"
    - name: ANOTHER_VARIABLE
      value: "another_value_here"
